
log file /var/log/sdplane.log

set l3fwd argv -c 0xf -- -p 0x3 --config="(0,0,2),(1,0,2)"
l3fwd init

# need to stop port before changing ports.
stop port all
set l2fwd l2fwd_enabled_port_mask 0x3
set l2fwd l2fwd_rx_queue_per_lcore 1
set worker lcore 1 l2fwd
set worker lcore 2 l2fwd
l2fwd init

# need to stop port before changing ports.
stop port all
set port all dev-configure 1 4

set worker lthread stat-collector
set worker lthread rib-manager
set worker lcore 1 l2-repeater
set worker lcore 2 l2-repeater
set worker lcore 3 tap-handler
set port all promiscuous enable
start port all

# queue config should be after rib-manager.
set thread 2 port 0 queue 0
set thread 2 port 1 queue 0

# waiting for the port to come up.
sleep 5
start worker lcore all
update port status

