frr version 8.4.4
frr defaults traditional
hostname sdplane
no service integrated-vtysh-config
!
interface rif1
 ipv6 ospf6 area 0.0.0.0
exit
!
interface rif2
 ipv6 ospf6 area 0.0.0.0
exit
!
router ospf
 network 198.18.1.0/24 area 0
 network 198.18.2.0/24 area 0
exit
!
router ospf6
exit