frr version 8.4.4
frr defaults traditional
hostname r2
no service integrated-vtysh-config
!
interface enp3s0
 ip address 198.18.2.10/24
 ipv6 address fd00:2::10/64
 ipv6 ospf6 area 0.0.0.0
exit
!
interface lo
 ip address 10.2.0.10/32
 ipv6 address 2001:2::10/128
 ipv6 ospf6 area 0.0.0.0
 ipv6 ospf6 passive
exit
!
router ospf
 network 10.2.0.10/32 area 0
 network 198.18.2.0/24 area 0
exit
!
router ospf6
exit
