
log file /var/log/sdplane.log
#log stdout

#debug sdplane fdb-change
#debug sdplane rib
#debug sdplane route-entry
#debug sdplane netlink
debug sdplane rib
#debug zcmdsh shell

set device 01:00.1 driver unbound
set device 01:00.1 driver vfio-pci driver_override
set device 01:00.1 driver vfio-pci bind

set device 02:00.0 driver unbound
set device 02:00.0 driver vfio-pci driver_override
set device 02:00.0 driver vfio-pci bind

set device 03:00.0 driver unbound
set device 03:00.0 driver vfio-pci driver_override
set device 03:00.0 driver vfio-pci bind

set rte_eal argv -c 0x7
#set rte_eal argv -l 2,3 -n 2
rte_eal_init
set mempool

set worker lcore 1 enhanced-repeater
set worker lcore 2 enhanced-repeater
set worker lcore 3 l3-tap-handler

set worker lthread rib-manager
set worker lthread netlink-thread
set worker lthread stat-collector
set worker lthread neigh-manager

# need to stop port before changing ports.
stop port all
set port all dev-configure 1 4
set port all nrxdesc 1024
set port all ntxdesc 1024

set port all promiscuous enable
start port all

# queue config should be after rib-manager.
set thread 1 port 0 queue 0
set thread 1 port 1 queue 0
set thread 2 port 0 queue 1
set thread 2 port 1 queue 1

set vswitch 10 vlan 10
set vswitch 10 port 0 untag
set vswitch 10 router-if port-1-00-1 vlan-id 1000

set vswitch 20 vlan 20
set vswitch 20 port 1 untag
set vswitch 20 router-if port-2-00-0

set vswitch 30 vlan 30
set vswitch 30 port 2 untag
set vswitch 30 router-if port-3-00-0

# library check.

set rte-flow action 0 index 0 end
set rte-flow action 1 index 0 queue 1
set rte-flow action 1 index 1 end
set rte-flow action 2 index 0 drop
set rte-flow action 2 index 1 end
# port 1 pattern 0 action 1 (queue 1)
set rte-flow-pattern 0 index 0 ipv4 zero
set rte-flow-pattern 0 index 0 ipv4 proto 89
set rte-flow-pattern 0 index 1 end
set rte-flow port 1 pattern 0 action 1
# port 0 pattern 1 action 2 (drop)
set rte-flow-pattern 1 index 0 ether any
set rte-flow-pattern 1 index 0 ether src 5e:3d:bb:8d:fe:52
set rte-flow-pattern 1 index 0 ether type 0x86dd
set rte-flow-pattern 1 index 1 vlan zero
set rte-flow-pattern 1 index 1 vlan id 100
set rte-flow-pattern 1 index 2 ipv4 zero
set rte-flow-pattern 1 index 2 ipv4 src 100.100.100.100
set rte-flow-pattern 1 index 2 ipv4 dst 200.200.200.200
set rte-flow-pattern 1 index 2 ipv4 proto 89
set rte-flow-pattern 1 index 3 end
set rte-flow port 0 pattern 1 action 2

# waiting for the port to come up.
sleep 5

# update port status
start worker lcore all


