log file /var/log/sdplane.log
log stdout

debug sdplane fdb-change
debug sdplane rib
debug sdplane l3-connector
debug sdplane tap-handler

set device 02:00.0 driver unbound
set device 02:00.0 driver vfio-pci driver_override
set device 02:00.0 driver vfio-pci bind

set device 03:00.0 driver unbound
set device 03:00.0 driver vfio-pci driver_override
set device 03:00.0 driver vfio-pci bind

set rte_eal argv -c 0x7
rte_eal_init

set worker lthread stat-collector
set worker lthread rib-manager
set worker lthread netlink-thread

set mempool

# queue config should be after rib-manager.
set thread 1 port 0 queue 0
set thread 1 port 1 queue 0

# need to stop port before changing ports.
stop port all
set port all dev-configure 1 4
set port all nrxdesc 1024
set port all ntxdesc 1024

set worker lcore 1 l3-connector
set worker lcore 2 l3-tap-handler
set port all promiscuous enable
start port all

# waiting for the port to come up.
sleep 5
update port status

set vswitch 10
set vswitch 20

set vswitch-link 0 0 0
set router-if 0 rif0
set capture-if 0 cif0

set vswitch-link 1 1 0
set router-if 1 rif1
set capture-if 1 cif1

# waiting for the vswitch setup
sleep 5
start worker lcore all