
log file /var/log/sdplane.log
log stdout
#debug sdplane packet
debug sdplane dhcp-server

set device 01:00.0 driver unbound
set device 01:00.0 driver vfio-pci driver_override
set device 01:00.0 driver vfio-pci bind

set device 01:00.1 driver unbound
set device 01:00.1 driver vfio-pci driver_override
set device 01:00.1 driver vfio-pci bind

set device 02:00.0 driver unbound
set device 02:00.0 driver vfio-pci driver_override
set device 02:00.0 driver vfio-pci bind

set device 03:00.0 driver unbound
set device 03:00.0 driver vfio-pci driver_override
set device 03:00.0 driver vfio-pci bind

set rte_eal argv -c 0xf
rte_eal_init
set mempool

set worker lthread rib-manager
set worker lthread stat-collector
set worker lthread neigh-manager
set worker lthread dhcp-server

set worker lcore 1 enhanced-repeater
set worker lcore 2 enhanced-repeater
set worker lcore 3 l3-tap-handler

stop port all
set port all dev-configure 1 4
set port all nrxdesc 1024
set port all ntxdesc 1024

set port all promiscuous enable
start port all

set thread 1 port 0 queue 0
set thread 1 port 1 queue 0
set thread 2 port 2 queue 0
set thread 2 port 3 queue 0

sleep 5

start worker lcore all

set vswitch 10 vlan 10
set vswitch 10 port 0 untag
set vswitch 10 router-if port-1-00-0
set vswitch 10 router-if port-1-00-0 hwaddr a8:b8:e0:05:9b:e1
set vswitch 10 router-if br10 hwaddr a8:b8:e0:05:9b:e1

set vswitch 11 vlan 11
set vswitch 11 port 1 untag
set vswitch 11 router-if port-1-00-1

set vswitch 12 vlan 12
set vswitch 12 port 2 untag
set vswitch 12 router-if port-2-00-0

set vswitch 13 vlan 13
set vswitch 13 port 3 untag
set vswitch 13 router-if port-3-00-0

