
log file /var/log/sdplane.log
log stdout

#debug sdplane fdb-change
#debug sdplane rib
debug sdplane stat-collector

set rte_eal argv -c 0xff
rte_eal_init
set mempool

set worker lthread rib-manager
set worker lthread stat-collector

#set worker lcore 1 enhanced-repeater
set worker lcore 2 l3-tap-handler
set worker lcore 3 vvf_vidsw
set worker lcore 4 vvf_vidsw


set vvf_vidsw 3 main port 0 rxqueue 0 txqueue 0
set vvf_vidsw 3 sub port 1 rxqueue 0 txqueue 0
set vvf_vidsw 3 out port 2 rxqueue 0 txqueue 0
set vvf_vidsw 3 main igmp_join src 192.168.34.222 addr 239.88.88.2
set vvf_vidsw 3 sub igmp_join src 192.168.34.222 addr 239.88.88.6

set vvf_vidsw 4 main port 0 rxqueue 1 txqueue 1
set vvf_vidsw 4 sub port 1 rxqueue 1 txqueue 1
set vvf_vidsw 4 out port 2 rxqueue 1 txqueue 1
set vvf_vidsw 4 main igmp_join src 192.168.34.223 addr 239.88.88.3
set vvf_vidsw 4 sub igmp_join src 192.168.34.223 addr 239.88.88.7

set vvf_vidsw mempool superjumbo 262143

# need to stop port before changing ports.
stop port all
set port all dev-configure 3 4
#set port all nrxdesc 1024
set port all nrxdesc 8192
set port all ntxdesc 1024

set port all promiscuous enable
start port all

# queue config should be after rib-manager.
#set thread 3 port 0 queue 0
#set thread 4 port 0 queue 1

# waiting for the port to come up.
sleep 5

# update port status
start worker lcore all

#set vswitch 10 vlan 10
#set vswitch 10 port 0 untag
#set vswitch 10 router-if port-1-00-1
#
#set vswitch 20 vlan 20
#set vswitch 20 port 1 untag
#set vswitch 20 router-if port-2-00-0
#
#set vswitch 30 vlan 30
#set vswitch 30 port 2 untag
#set vswitch 30 router-if port-3-00-0

set rte-flow-pattern 0 index 0 end

#set rte-flow-pattern 0 index 0 ether any
#set rte-flow-pattern 0 index 1 end

#set rte-flow-pattern 0 index 0 ether any
#set rte-flow-pattern 0 index 1 vlan zero
#set rte-flow-pattern 0 index 1 vlan id 100
#set rte-flow-pattern 0 index 2 ipv4 zero
#set rte-flow-pattern 0 index 2 ipv4 src 100.100.100.100
#set rte-flow-pattern 0 index 2 ipv4 dst 200.200.200.200
#set rte-flow-pattern 0 index 3 end

#set rte-flow port 0 pattern 0 action queue 1
#set rte-flow port 0 pattern 0 action drop
set rte-flow port 0 pattern 0 action none

set rte-flow-pattern 1 index 0 end

#set rte-flow-pattern 1 index 0 ether any
#set rte-flow-pattern 1 index 1 end

#set rte-flow-pattern 1 index 0 ether any
#set rte-flow-pattern 1 index 1 vlan zero
#set rte-flow-pattern 1 index 1 vlan id 200
#set rte-flow-pattern 1 index 2 ipv4 zero
#set rte-flow-pattern 1 index 2 ipv4 src 100.100.100.100
#set rte-flow-pattern 1 index 2 ipv4 dst 200.200.200.200
#set rte-flow-pattern 1 index 3 end
set rte-flow port 0 pattern 1 action queue 2

