name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-24.04
    env:
      DPDK_VERSION: 23.11.1
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            cmake \
            python3 \
            python3-pip \
            meson \
            ninja-build \
            python3-pyelftools \
            libnuma-dev \
            pkgconf \
            liburcu-dev \
            libpcap-dev

      - name: Install lthread
        run: |
          cd ${HOME}
          git clone https://github.com/yasuhironet/lthread.git
          cd lthread
          cmake .
          make
          sudo make install

      - name: Cache DPDK
        id: cache-dpdk
        uses: actions/cache@v4
        env:
          cache-name: cache-dpdk
        with:
          path: ~/dpdk-stable-${{ env.DPDK_VERSION }}
          key: ${{ runner.os }}-dpdk-${{ env.DPDK_VERSION }}

      - name: Build DPDK
        if: ${{ steps.cache-dpdk.outputs.cache-hit != 'true' }}
        run: |
          cd ${HOME}
          wget https://fast.dpdk.org/rel/dpdk-${DPDK_VERSION}.tar.xz
          tar -xvJf dpdk-${DPDK_VERSION}.tar.xz
          cd dpdk-stable-${DPDK_VERSION}
          meson setup build
          cd build
          ninja

      - name: Install DPDK
        run: |
          cd ${HOME}/dpdk-stable-${DPDK_VERSION}/build
          sudo meson install
          sudo ldconfig

      - name: Install libsdplane
        run: |
          wget https://www.yasuhironet.net/download/partaker/libsdplane_0.3.36-52_amd64.deb
          sudo apt-get install -y ./libsdplane_0.3.36-52_amd64.deb

      - name: Build sdplane
        run: |
          aclocal
          autoheader
          automake -a -c
          autoconf
          mkdir build
          cd build
          ../configure
          make
