name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build with DPDK ${{ matrix.dpdk_version }}
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        dpdk_version:
          - "23.11.5"
          - "24.11.3"
          # - "25.07"
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            cmake \
            python3 \
            python3-pip \
            meson \
            ninja-build \
            python3-pyelftools \
            libnuma-dev \
            pkgconf \
            liburcu-dev \
            libpcap-dev

      - name: Install lthread
        run: |
          cd ${HOME}
          git clone https://github.com/yasuhironet/lthread.git
          cd lthread
          cmake .
          make
          sudo make install

      - name: Cache DPDK
        id: cache-dpdk
        uses: actions/cache@v4
        env:
          cache-name: cache-dpdk
        with:
          path: ~/dpdk-${{ matrix.dpdk_version }}.pkg.tar.gz
          key: ${{ runner.os }}-dpdk-${{ matrix.dpdk_version }}

      - name: Build DPDK
        if: ${{ steps.cache-dpdk.outputs.cache-hit != 'true' }}
        run: |
          cd ${HOME}
          wget https://fast.dpdk.org/rel/dpdk-${{ matrix.dpdk_version }}.tar.xz
          tar -xvJf dpdk-${{ matrix.dpdk_version }}.tar.xz
          ls dpdk-${{ matrix.dpdk_version }} || mv dpdk-stable-${{ matrix.dpdk_version }} dpdk-${{ matrix.dpdk_version }}
          cd dpdk-${{ matrix.dpdk_version }}
          meson setup build
          cd build
          ninja
          DESTDIR=$PWD/pkg meson install
          tar --owner=0 --group=0 -czf ~/dpdk-${{ matrix.dpdk_version }}.pkg.tar.gz -C pkg .

      - name: Install DPDK
        run: |
          sudo tar -xzf ~/dpdk-${{ matrix.dpdk_version }}.pkg.tar.gz -C /
          sudo ldconfig

      - name: Install libsdplane
        run: |
          wget https://www.yasuhironet.net/download/n305/libsdplane_0.3.37-73_amd64.deb
          sudo apt-get install -y ./libsdplane_0.3.37-73_amd64.deb

      - name: Build sdplane
        run: |
          ./autogen.sh
          mkdir build
          cd build
          ../configure
          make -j$(nproc)
